tap "homebrew/bundle"
brew "mas"
brew "pure"
brew "tmux"
cask "bettertouchtool"
cask "discord"
cask "flux"
cask "google-chrome"
cask "monitorcontrol"
cask "notion"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "Bear", id: 1091189122
